QtQuickVcp.pro, src/application/ApplicationCore.qml, src/application/ApplicationHelper.qml, src/application/ApplicationItem.qml, src/application/ApplicationObject.qml, src/application/ApplicationSettings.qml, src/application/HomeAllAxesHelper.qml, src/application/application.pro, src/application/application.qrc, src/application/plugin.cpp, src/application/qmldir, src/applicationcontrols/AxisComboBox.qml, src/applicationcontrols/AxisRadioGroup.qml, src/applicationcontrols/DigitalReadOut.qml, src/applicationcontrols/JogVelocityHandler.qml, src/applicationcontrols/MaximumVelocityHandler.qml, src/applicationcontrols/TouchOffDialog.qml, src/pathview/PathView3D.qml, src/pathview/PathViewCore.qml, src/pathview/ProgramExtents3D.qml, src/pathview/ProgramOffsets3D.qml, src/pathview/qglpathitem.cpp, src/pathview/qglpathitem.h, tests/qmltests/qmltests.pro, tests/qmltests/tst_ApplicationObject.qml, tests/qmltests/tst_qml.cpp, tests/tests.pro
* rework of the PathView
* fixes for unit system
* more generic axis handling
=> Pathview rework

src/application/qapplicationcommand.cpp, src/application/qapplicationconfig.cpp, src/application/qapplicationerror.cpp, src/application/qapplicationfile.cpp, src/application/qapplicationlauncher.cpp, src/application/qapplicationstatus.cpp, src/halremote/qhalgroup.cpp, src/halremote/qhalpin.cpp, src/halremote/qhalpin.h, src/halremote/qhalremotecomponent.cpp, src/halremote/qhalremotecomponent.h, src/pathview/qgcodeprogramitem.cpp, src/pathview/qgcodeprogramloader.cpp, src/pathview/qglcanvas.cpp, src/pathview/qglcubeitem.cpp, src/pathview/qglcylinderitem.cpp, src/pathview/qglpathitem.cpp, src/pathview/qglpathitem.h, src/pathview/qglsphereitem.cpp, src/pathview/qglview.cpp, src/pathview/qglview.h, src/pathview/qpreviewclient.cpp, src/service/qnameserver.cpp, src/service/qservicediscovery.cpp, src/videoview/qmjpegstreamerclient.cpp
Adds support for using HAL remote components without bind
=> Halremote pins

3rdparty/machinetalk-protobuf/src/machinetalk/protobuf/preview.proto, src/pathview/PathView3D.qml, src/pathview/PathViewCore.qml, src/pathview/qgcodeprogramitem.cpp, src/pathview/qgcodeprogramitem.h, src/pathview/qgcodeprogrammodel.cpp, src/pathview/qgcodeprogrammodel.h, src/pathview/qglpathitem.cpp, src/pathview/qglpathitem.h, src/pathview/qpreviewclient.cpp, src/pathview/qpreviewclient.h
* removed unit conversion due to update of `previewmodule.cc`
* using `PV_PREVIEW_START` and `PV_PREVIEW_END`
* storing preview items in additional list since file and line numbers do not always match preview sequence
=> Preview update

src/application/application.pro, src/application/fileio.cpp, src/application/fileio.h, src/application/plugin.cpp, src/pathview/qglpathitem.cpp
The FileIO component allow reading and writing text files from QML.
=> add FileIO component

3rdparty/nzmqt/3rdparty/cppzmq/zmq.hpp
fixes compile problems on Ubuntu 16.04
=> updated zmq.hpp

apps/MachinekitClient/main.qml, build/travis/job2_AppImage/build.sh, src/application/application.pro, src/application/plugin.cpp, src/application/revision.h, src/application/revisionsingleton.h
adding revision number to QtQuickVcp and MachinekitClient
=> Revision number

src/common/service.cpp, src/common/service.h
Enables Machinetalk array delete functionality. Matches: https://github.com/machinekit/machinekit/pull/1071
=> common/service: enabling deleting of array entries

appveyor.yml, build/appveyor/appveyor.bat, src/protobuf.pri
Adding CI for Windows using AppVeyor.
=> Adding CI for Windows

src/applicationcontrols/RunProgramAction.qml, src/pathview/SourceView.qml
* Fix RunProgramAction beeing active when jog is running
* Fix line break in GCode preview
=> Small fixes

src/application/ApplicationCore.qml, src/application/qapplicationfile.cpp, src/application/qapplicationfile.h, src/applicationcontrols/ApplicationRemoteFileDialog.qml
Adds support for browsing folders to ApplicationFile.
=> Support for remote folders

.travis.yml, README.md
* Adds Download links and build status to README
* Adds MachinekitClient stuff to README
* disables zsync
=> README updates and build updates

.travis.yml, build/travis/job_macos/before_install.sh, build/travis/job_macos/bintray-tidy.sh, build/travis/job_macos/bintray_app.sh, build/travis/job_macos/build.sh, build/travis/job_macos/extract-qt-installer, build/travis/job_macos/install.sh
Continuous integration for Mac OS X builds
=> Mac OS X CI

src/pathview/PathViewCore.qml, src/pathview/PathViewObject.qml
* exposing previewClient
* disconnect preview update functions
=> Pathview updates

src/applicationcontrols/ConnectionWindow.qml, src/applicationcontrols/Private/InstancePage.qml
=> ConnectionWindow: fix binding loop

src/applicationcontrols/GCodeLabel.qml
fixes https://github.com/machinekoder/QtQuickVcp/issues/125
=> GCodeLabel: fix mixed up desiredGCodes and MCodes

src/application/ApplicationHelper.qml
=> Get distance factor based on machine units and interp units

src/application/applicationlauncher.cpp, src/application/applicationstatus.cpp, src/machinetalk/machinetalkservice.cpp, src/machinetalk/machinetalkservice.h, src/pathview/previewclient.cpp
* using pass by reference
* use C++ style casts
=> Code Cleanup

src/halremote/halpin.cpp, src/halremote/halpin.h, tests/halremotetests/halremotetests.pro, tests/halremotetests/tst_halpintest.cpp, tests/tests.pro
* use const references
* add unit tests
* add queuing property
=> HalPin update

src/application/ApplicationCore.qml, src/application/QueuedConnection.qml, src/application/application.pro, src/application/application.qrc, src/application/plugin.cpp, src/application/qmldir, src/pathview/PathViewCore.qml
prevents binding loops problems for synced and connected states
=> Application: adding QueuedConnection

src/halremote/halpin.cpp, src/halremote/halpin.h, tests/halremotetests/tst_halpintest.cpp
Partially reverts https://github.com/machinekoder/QtQuickVcp/pull/130
=> HalPin: remove queuing feature

src/application/application.pro, src/applicationcontrols/applicationcontrols.pro, src/controls/controls.pro, src/halremote/halremote.pro, src/halremotecontrols/halremotecontrols.pro, src/pathview/pathview.pro
Partially reverts: https://github.com/machinekoder/QtQuickVcp/pull/136
=> Revert QQC patch

src/application/HomeAllAxesHelper.qml, src/applicationcontrols/HomeAxisAction.qml
The Axis shows the Home All button only when applicable. This patch adds this feature also for QtQuickVcp based UIs.
=> Homing sequence like Axis

appveyor.yml, build/Linux/android/Recipe, build/Linux/portable/Recipe, build/appveyor/appveyor.bat, build/travis/job2_AppImage/bintray_lib.sh, build/travis/job2_AppImage/build.sh, build/travis/job3_Android/build.sh, build/travis/job_macos/bintray_lib.sh, build/travis/job_macos/build.sh
* adds latest versions for QtQuickVcp for easier integration into other CIs
* adds QtQuickVcp package for MacOSX
=> continuous deployment update

.gitignore, src/application/ApplicationSettings.qml, src/applicationcontrols/AbstractDigitalReadOut.qml, src/applicationcontrols/DigitalReadOut.qml, src/applicationcontrols/JogDistanceHandler.qml, src/applicationcontrols/applicationcontrols.pro, src/applicationcontrols/plugin.cpp, src/applicationcontrols/qmldir, src/pathview/PathView3D.qml, tests/qmltests/qmltests.pro, tests/qmltests/tst_JogDistanceHandler.qml
* Moves Continous to front in JogDistanceHandler
* decreases tool size in PathView
* save settings per machine and UI
* adds and abstract DRO for new DROs to be based on
* adds support for Axis-style increments
=> Controls update

src/applicationcontrols/HomeAxisAction.qml
fixes bug introduced by https://github.com/QtQuickVcp/QtQuickVcp/pull/140
=> HomeAxisAction: fix broken homing

src/application/applicationdescription.cpp, src/application/applicationplugins.cpp, src/applicationcontrols/ServiceWindow.qml, src/halremote/halremotecomponent.cpp, src/machinetalk/application/errorsubscribe.cpp, src/machinetalk/application/launchersubscribe.cpp, src/machinetalk/application/statussubscribe.cpp, src/machinetalk/common/subscribe.cpp, src/machinetalk/halremote/halrcompsubscribe.cpp, src/machinetalk/pathview/previewsubscribe.cpp, src/pathview/glpathitem.cpp, src/pathview/glpathitem.h, src/pathview/glview.cpp, src/pathview/glview.h, src/service/nameserver.cpp, src/service/servicediscovery.cpp, src/service/servicediscoveryitem.cpp
* removes static analyzer warnings in GLView
* cleans up dead code in GLView
* replaces foreach with C++11 for of loop
=> Code cleanup and GLView fix

src/pathview/PathView3D.qml, src/pathview/glpathitem.cpp, src/pathview/glpathitem.h, src/pathview/glview.cpp, src/pathview/glview.h
Axis supports setting the precision of arc rendered to the screen and so should we.
=> adding support for [DISPLAY]ARCDIVSION

3rdparty/jdns/src/jdns/jdns.c, 3rdparty/jdns/src/jdns/jdns_sys.c, 3rdparty/jdns/src/qjdns/qjdns.cpp
Contains the next set of fixes.
=> Fixes for problems reported by Coverity Scan

src/machinetalk/application/errorsubscribe.cpp, src/machinetalk/application/errorsubscribe.h
fixes problem in ApplicationError
=> Machinetalk: update from machinetalk-gsl

src/machinetalk/application/commandbase.h, src/machinetalk/application/configbase.h, src/machinetalk/application/errorbase.h, src/machinetalk/application/errorsubscribe.cpp, src/machinetalk/application/errorsubscribe.h, src/machinetalk/application/launcherbase.h, src/machinetalk/application/launchersubscribe.cpp, src/machinetalk/application/launchersubscribe.h, src/machinetalk/application/statusbase.h, src/machinetalk/application/statussubscribe.cpp, src/machinetalk/application/statussubscribe.h, src/machinetalk/common/rpcclient.cpp, src/machinetalk/common/rpcclient.h, src/machinetalk/common/subscribe.cpp, src/machinetalk/common/subscribe.h, src/machinetalk/halremote/halrcompsubscribe.cpp, src/machinetalk/halremote/halrcompsubscribe.h, src/machinetalk/halremote/remotecomponentbase.h, src/machinetalk/param/paramclient.h, src/machinetalk/param/paramserver.h, src/machinetalk/pathview/previewclientbase.h, src/machinetalk/pathview/previewsubscribe.h
* Drastically increase the default heartbeat liveness to get rid of disconnection errors.
* Fix leftover pass by values.
=> Improvements for Machinetalk

3rdparty/jdns/src/jdns/jdns.c, 3rdparty/machinetalk-protobuf-qt/machinetalk-protobuf-qt.pro, src/service/debughelper.h, src/service/nameserver.cpp, src/service/nameserver.h, src/service/service.h, src/service/servicediscovery.cpp, src/service/servicediscovery.h, src/service/servicediscoveryfilter.cpp, src/service/servicediscoveryfilter.h, src/service/servicediscoveryitem.cpp, src/service/servicediscoveryitem.h, src/service/servicediscoveryquery.cpp, src/service/servicediscoveryquery.h, src/service/servicelist.h, src/videoview/proto/package.proto, tests/servicediscoverytests/qjdns_stub.cpp, tests/servicediscoverytests/servicediscoverytests.pro, tests/servicediscoverytests/tst_servicediscoverytest.cpp, tests/tests.pro
Cleans up problems in the ServiceDiscovery. Should fix Unicast problems under Windows 10.
=> Cleaning and reworking ServiceDiscovery

3rdparty/catch/catch.hpp, 3rdparty/catch/catch.pri, 3rdparty/trompeloeil/trompeloeil.hpp, 3rdparty/trompeloeil/trompeloeil.pri, 3rdparty/trompeloeil/trompeloeil_catch.hpp, README.md, tests/halremotetests/halremotetests.pro, tests/halremotetests/main.cpp, tests/halremotetests/tst_halpintest.cpp
This PR adds better testing capabilities to QtQuickVcp by using Catch and Trompeloil.
=> Better Unit testing

src/application/applicationconfig.cpp, src/application/applicationconfig.h, src/application/applicationfile.cpp, src/application/applicationfile.h, src/application/applicationlauncher.cpp, src/application/applicationlauncher.h, src/applicationcontrols/Private/LauncherPage.qml, src/machinetalk/machinetalkservice.cpp, src/machinetalk/machinetalkservice.h
* Fixes bug in LauncherPage
* use QTemporaryDir instead of custom method
=> Fixes and improvements

paths.pri, src/application/applicationfile.h
couple of fixes
i got errors trying it thru machinekit-vagrant
=> build fails on vagrant debian virtualbox

src/applicationcontrols/ToolTableEditor.qml, src/applicationcontrols/ToolTableEditorDialog.qml
Adds support for keyboard navigation to the tool table editor.
=> Tool table keyboard navigation support

src/applicationcontrols/RunProgramAction.qml, src/pathview/SourceView.qml, src/pathview/translations/machinekitpathview_de.ts, src/pathview/translations/machinekitpathview_en.ts, src/pathview/translations/machinekitpathview_ru.ts
Adds run from here to the GCode SourceView menu.
=> Add run from here

apps/MachinekitClient/main.qml, src/applicationcontrols/ConnectionWindow.qml, src/halremote/halremotecomponent.cpp, src/service/servicediscovery.cpp, src/service/servicediscovery.h
This PR adds some syntactic sugar to improve the QML syntax of QtQuickVcp.
=> Nicer QML Syntax

debian/control
A couple more deps for debian packaging, and replace a missing comma
=> debian/control:  add missing qml modules

src/pathview/PathView3D.qml
Not sure if is actually a valid solution, but it works for me :) this should fix #219. Not sure how to to run tests, maybe this PR could be an inspiration for someone with actual knowledge here ;)
=> Change programExtents and path position to g5x offset

src/applicationcontrols/Private/AppPage.qml
Useful to debug: https://github.com/qtquickvcp/QtQuickVcp/issues/218
=> AppPage: show better QML error messages

src/service/service.cpp, src/service/servicediscovery.cpp, src/service/servicediscovery.h
Multiple discovered services caused uncompleted services to be used a
service reference.
=> ServiceDiscovery: fix race condition

src/applicationcontrols/ServiceWindow.qml, src/halremotecontrols/HalApplicationWindow.qml
=> ServiceWindow: add click stealing

apps/MachinekitClient/init.qml, playground/ApplicationRemoteFileDialogTest.qml, src/applicationcontrols/ApplicationRemoteFileDialog.qml, src/applicationcontrols/JogDistanceComboBox.qml, src/applicationcontrols/JogVelocityHandler.qml, src/applicationcontrols/Private/LauncherPage.qml, tests/qmltests/qmltests.pro, tests/qmltests/tst_LauncherPage.qml
* some code cleanup
* JogDistanceComboBox: save user values
* LauncherPage: correct launcher order
* ApplicationRemoteFileDialog: highlight folders
* MachinekitClient: fix x,y position
=> Another set of improvements

src/application/ApplicationCore.qml, src/applicationcontrols/ApplicationProgressBar.qml, src/applicationcontrols/ApplicationRemoteFileDialog.qml, src/applicationcontrols/JogDistanceComboBox.qml, src/applicationcontrols/Private/SelectedPage.qml, src/pathview/PathViewCore.qml
* QML/code cleanups
* fix bug in ApplicationRemoteFileDialog
* PathViewCore: unload program completely
=> Next set of improvements

src/application/applicationfile.h, src/applicationcontrols/ApplicationRemoteFileDialog.qml, src/pathview/BoundingBox3D.qml, src/pathview/ProgramExtents3D.qml, src/pathview/ProgramOffsets3D.qml, tests/applicationtests/test_applicationfile.cpp
A set of improvement for QtQuickVcp under Windows.
=> Improvements for Windows

src/application/ApplicationCore.qml, src/applicationcontrols/ApplicationFileDialog.qml
remotePath was not set correctly.
=> Fix for problems with local upload

src/applicationcontrols/DigitalReadOut.qml, src/pathview/glitem.cpp, src/pathview/glitem.h, src/pathview/glview.cpp
Small continuous steps to a better QtQuickVcp.
=> Small improvements

tests/applicationtests/test_filewatcher.cpp
This is a problem on Travis CI it seems.
=> tests: FileWatcher tests may fail on some systems

src/pathview/glpathitem.cpp, src/pathview/glpathitem.h, src/pathview/glview.cpp
Finally, fixing the broken G2/G3 preview implementation:
https://github.com/machinekit/QtQuickVcp/issues/248
=> pathview: fix G2/G3 preview

src/application/applicationplugins.cpp, src/application/applicationplugins.h, src/pathview/ProgramOffsets3D.qml
* Fixes G92 preview line missing.
* Use const reference for ApplicationPlugins
=> Fix for G92 preview and code cleanup

src/applicationcontrols/AbstractDigitalReadOut.qml, src/applicationcontrols/DigitalReadOut.qml, src/applicationcontrols/translations/machinekitapplicationcontrols_de.ts, src/applicationcontrols/translations/machinekitapplicationcontrols_en.ts, src/applicationcontrols/translations/machinekitapplicationcontrols_ru.ts, src/pathview/PathView3D.qml, src/pathview/ProgramExtents3D.qml, src/pathview/ViewModeAction.qml, src/pathview/glitem.cpp, src/pathview/glitem.h, src/pathview/glview.cpp
This patch adds lathe support to QtQuickVcp. In particular, it adds support for lathe preview and lathe mode jogging.
=> Implement lathe support

apps/MachinekitClient/MachinekitClient.LiveCoding/LiveCoding.qml, src/applicationcontrols/ConnectionWindow.qml
This patch adds useful information to the title bar of Machinekit Client and co.
=> Show current instance in title bar

apps/MachinekitClient/translation.pri, build/appveyor/appveyor.bat, src/applicationcontrols/ConnectionWindow.qml, src/applicationcontrols/Private/LanguageControlButton.qml, src/translation.pri
FIxes deployment of the translations for Windows.
=> Windows translations deployment

src/application/applicationstatus.cpp, src/application/applicationstatus.h
Fixes incompatibilities with older Machinekit versions.
=> application/ApplicationStatus: make the UiChannel optional

src/application/filewatcher.cpp, src/application/filewatcher.h, tests/applicationtests/test_filewatcher.cpp
More robust file watching for QML.
=> application: improve FileWatcher

src/application/plugin/plugin.cpp, src/applicationcontrols/plugin/plugin.cpp, src/controls/plugin/plugin.cpp, src/halremotecontrols/plugin/plugin.cpp, src/pathview/glview.cpp, src/pathview/glview.h, src/pathview/plugin/plugin.cpp
* use the first type in the list of QML files instead of name for qrc detection
* GLView: fix crash when window does not exist yet
=> Small set of fixes

src/application/ApplicationCore.qml, src/application/applicationfile.cpp, src/applicationcontrols/ApplicationFileDialog.qml, src/pathview/PathViewCore.qml
Execute the preview for any file, not only .ngc files.
=> PathViewCore: execute preview for anything

src/videoview/mjpegstreamerclient.cpp
This PR is just for bumping the version number to create a new build.
=> bump version

build/travis/job_macos/bintray_app.sh, build/travis/job_macos/bintray_lib.sh
Hopefully re-enables the OSX builds.
=> build: use posix sed -E instead of -r
